
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    environment:
      MYSQL_DATABASE: tp_formation
      MYSQL_ROOT_PASSWORD: root
      # You should definitely change the password in production
      MYSQL_PASSWORD: pwd
      MYSQL_USER: usr
    volumes:
      - database_data:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
